[package]
name = "containerd-shim-wasm"
description = "Library for building containerd shims for wasm"
version = "0.2.1"
edition.workspace = true
license.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
git-version = "0.3.5"
containerd-shim = { workspace = true }
crossbeam = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
oci-spec = { workspace = true }
protobuf = "3.2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ttrpc = { workspace = true }
wat = { workspace = true }

[target.'cfg(unix)'.dependencies]
caps = "0.5"
dbus = { version = "*", optional = true }
libcontainer = { workspace = true, optional = true, default-features = false }
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[build-dependencies]
ttrpc-codegen = { version = "0.4.2", optional = true }

[dev-dependencies]
tempfile = "3.8"

[features]
default = []
libcontainer_default = ["libcontainer/default", "dbus/vendored"]
generate_bindings = ["ttrpc-codegen"]
generate_doc = []
libseccomp = ["libcontainer/libseccomp"]
systemd = ["libcontainer/systemd", "dbus/vendored"]
cgroupsv2 = ["libcontainer/v2"]
cgroupsv1 = ["libcontainer/v1"]
cgroupsv2_devices = ["libcontainer/cgroupsv2_devices"]

[package.metadata.cargo-all-features]
skip_feature_sets = [
    ["cgroupsv2", "cgroupsv2_devices"],
    ["cgroupsv1", "cgroupsv2_devices"],
    ["libcontainer_default", "cgroupsv2_devices"],
    ["systemd", "cgroupsv2_devices"],
    ["generate_bindings", "generate_doc"]
]
skip_optional_dependencies = true
max_combination_size = 3
