version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      wasmtime-deps:
        patterns:
          - "wasmtime"
          - "wasmtime-common"
          - "wasi-common"

